### ISSUE TITLE
Project plan?

### ISSUE THREAD

**Issue by mattlinares** [Gagaro/wagtail-calendar#1]
Hi there,

I'm very interested in the plan for this repo. What do you intend to do with this?

Thanks!

**Comment by Gagaro** [comment]
Hi @mattlinares ,

Sorry for not answering you earlier, but I actually didn't watched this repository and thus didn't get the notification.. I originally planned to work on this last month but I got caught by life. Hopefully I'll have more time to finish this now.

The idea for this module is to display a calendar ([fullcalendar](https://fullcalendar.io/)) with all the published and planned pages inside (this part is done, see the `README` for a todo list).

The next step would be to be able to simply drag'n'drop them to change the publication date and time. This would include the page which are not planned yet (something like [that](https://fullcalendar.io/js/fullcalendar-3.5.1/demos/external-dragging.html)).

If you have more idea, don't hesitate to talk about them.

**Comment by mattlinares** [comment]
Thanks Gagaro, that looks great.

We are considering building something like this, possibly with more features, such as:

- some calendar design work to show more information on each post entry
- the possibility to list other sorts of entries e.g. events, so that people can see contextual information e.g. projects, major events.
- email notifications on post creation and on event update
- email notifications filtered by tag so people receive notifications of scheduled post they are interested in

What kind of site do you intend to use this for? It’d be interesting to chat to you about your development plan more directly. Please email me if possible matthew.linares@opendemocracy.net.

**Comment by Gagaro** [comment]
> * some calendar design work to show more information on each post entry

What kind of information of you have in mind? And how are you thinking about displaying those information?

I thought about adding a popup on click to show more such as a link to edit, a link to live version, etc. But I'm not sure what would be pertinent to add there.

> * the possibility to list other sorts of entries e.g. events, so that people can see contextual information e.g. projects, major events.

Yes, I thought about that too. I'm going to change what I made to use a hook. That way, any module could add anything.

> * email notifications on post creation and on event update
> * email notifications filtered by tag so people receive notifications of scheduled post they are interested in

I don't think that those points are in the scope of this module.

> What kind of site do you intend to use this for?

It's for a simple blog.

**Comment by mattlinares** [comment]
> some calendar design work to show more information on each post entry
> What kind of information of you have in mind? And how are you thinking about displaying those information?
> 
> I thought about adding a popup on click to show more such as a link to edit, a link to live version, etc. But I'm not sure what would be pertinent to add there.

It would be good to add a post title, a post author, subject tags, and maybe a very short post description. It might be good to colour code them too to indicate if they come from a particular project/section, etc.

> email notifications on post creation and on event update
> email notifications filtered by tag so people receive notifications of scheduled post they are interested in
> I don't think that those points are in the scope of this module.

I think that's probably true.

I think I know some other people working on similar stuff so it might be useful to share ideas. Get in touch if you are working on this soon. Thanks

**Comment by Gagaro** [comment]
> It would be good to add a post title, a post author, subject tags, and maybe a very short post description.

I agree

> It might be good to colour code them too to indicate if they come from a particular project/section, etc.

This would be specific stuff. It could be done in the hooks.

> I think I know some other people working on similar stuff so it might be useful to share ideas. Get in touch if you are working on this soon.

I'll send you a mail.
