### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by tomdyson** [Gagaro/wagtail-calendar#2]
Hi @Gagaro - can you provide a screenshot in the README? Even if the app isn't finished yet, it would be great to understand more what we can expect to see. There's a lot of interest in editorial planning / calendars at the current Wagtail sprint in Bristol. Thanks!

**Comment by Gagaro** [comment]
Sure, I added two of them.

This is still very early though, so of course there's a lot of room for improvement.

**Comment by tomdyson** [comment]
Thanks @Gagaro - this looks great!
